Repository braintree-go/braintree-go, pull requests merged in 2018-05, with the labels that each got.

#220 Add StatusHistory to Subscription
  subscription.go
  subscription_integration_test.go
  subscription_status_history.go
Labels: enhancement

#224 Added CreatedAt and UpdatedAt fields for Customer struct (fixes #223)
  customer.go
  customer_integration_test.go
Labels: enhancement

#222 Rewrite validation errors handling
  CHANGELOG.md
  errors.go
  errors_test.go
  transaction_integration_test.go
  webhook_notification.go
Labels: breaking-change, bug, enhancement, refactor / internal

#221 Add RetryCharge function
  subscription.go
  subscription_gateway.go
  subscription_integration_test.go
Labels: enhancement

#232 Fix errcheck fmt.Fprintf analysis failure
  examples/transaction/server.go
Labels: refactor / internal

#214 Add transaction line items
  CHANGELOG.md
  braintree.go
  response.go
  transaction.go
  transaction_line_item.go
  transaction_line_item_gateway.go
  transaction_line_item_gateway_test.go
Labels: enhancement
