Repository braintree-go/braintree-go, pull requests merged in 2018-07, with the labels that each got.

#246 Add SearchPage to TransactionGateway and SubscriptionGateway
  search.go
  subscription_gateway.go
  subscription_integration_test.go
  transaction_gateway.go
  transaction_integration_test.go
Labels: enhancement

#247 Add SearchPage to TransactionGateway and SubscriptionGateway
  search.go
  subscription_gateway.go
  subscription_integration_test.go
  transaction_gateway.go
  transaction_integration_test.go
Labels: enhancement

#244 Add method ExpiringBetween to CreditCardGateway
  credit_card.go
  credit_card_gateway.go
  credit_card_integration_test.go
Labels: enhancement

#251 Correct test documentation
  README.md
Labels: bug

#254 Remove the apicompat backwards compatibility check
  .travis.yml
  Makefile
Labels: refactor / internal

#255 Add go tip and next beta to tests
  .travis.yml
Labels: refactor / internal

#258 Allow Transaction RiskData ID to be empty if not evaluated
  transaction_integration_test.go
Labels: bug

#257 Better customer search with paging (fixes #256)
  customer.go
  customer_gateway.go
  customer_integration_test.go
Labels: enhancement

#253 Intoduce 3DS support (bis repetita) (continued)
  braintree.go
  examples/transaction_3ds/form.html
  examples/transaction_3ds/result.html
  examples/transaction_3ds/server.go
  payment_method_nonce.go
  payment_method_nonce_gateway.go
  payment_method_nonce_integration_test.go
  response.go
  three_d_secure.go
  transaction.go
  transaction_3ds_integration_test.go
Labels: enhancement
